"""Add contribution_reference to contributions table

Revision ID: dc1469b7c469
Revises: 35c91e0a9dba
Create Date: 2023-12-25 12:53:47.568368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1469b7c469'
down_revision = '35c91e0a9dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('contribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fundraiser_id', sa.Integer(), nullable=False),
    sa.Column('contribution_reference', sa.Text(), nullable=False),
    sa.Column('contributor_name', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('contribution_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser.id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.drop_table('contribution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fundraiser_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contributions')
    # ### end Alembic commands ###
